// Sample notifications extracted from the original Lovable seed migration.
// Date fields are day offsets relative to the day you run the seed, so deadline colours always show.
export type SeedNotice = {
  org: string; title: string; titleHi: string; summary: string; summaryHi: string;
  postNames: string[]; adv: string; vacancies: number; breakup: Record<string, number>;
  state: string; location: string; qual: string; qualDetails: string; streams: string[];
  minAge: number; maxAge: number; cutoff: number | null; relax: Record<string, number>; exp: number;
  fees: Record<string, number>; selection: string; pay: string;
  notif: number; applyStart: number; applyLast: number; exam: number | null; admit: number | null;
  pdf: string; apply: string; src: string;
};

export const SEED_NOTICES: SeedNotice[] = [
  {"org": "SSC", "title": "SSC Combined Graduate Level Examination 2026", "titleHi": "एसएससी संयुक्त स्नातक स्तरीय परीक्षा 2026", "summary": "Recruitment to Group B and Group C posts in ministries and departments of the Government of India.", "summaryHi": "भारत सरकार के मंत्रालयों में ग्रुप बी और ग्रुप सी पदों पर भर्ती।", "postNames": ["Assistant Section Officer", "Inspector (Income Tax)", "Auditor"], "adv": "SSC/CGL/01/2026", "vacancies": 17727, "breakup": {"UR": 7000, "OBC": 4500, "SC": 2700, "ST": 1400, "EWS": 2127}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Bachelor's degree in any discipline from a recognised university.", "streams": ["Any"], "minAge": 18, "maxAge": 32, "cutoff": 90, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 3}, "exp": 0, "fees": {"general": 100, "obc": 100, "ews": 100, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Tier I (CBT) -> Tier II (CBT) -> Document Verification", "pay": "Pay Level 4 to 8 (Rs 25,500 - 1,51,100)", "notif": -12, "applyStart": -10, "applyLast": 2, "exam": 45, "admit": 60, "pdf": null, "apply": "https://ssc.gov.in/notice/cgl-2026.pdf", "src": "https://ssc.gov.in/apply"},
  {"org": "SSC", "title": "SSC Combined Higher Secondary Level (10+2) Exam 2026", "titleHi": "एसएससी संयुक्त उच्चतर माध्यमिक स्तर परीक्षा 2026", "summary": "Recruitment of LDC, JSA and Data Entry Operators across central government offices.", "summaryHi": "केंद्र सरकार कार्यालयों में एलडीसी, जेएसए और डीईओ की भर्ती।", "postNames": ["Lower Division Clerk", "Data Entry Operator"], "adv": "SSC/CHSL/02/2026", "vacancies": 3712, "breakup": {"UR": 1500, "OBC": 900, "SC": 600, "ST": 330, "EWS": 382}, "state": "All India", "location": "All India", "qual": "12th", "qualDetails": "12th pass from a recognised board.", "streams": ["Any"], "minAge": 18, "maxAge": 27, "cutoff": 90, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 3}, "exp": 0, "fees": {"general": 100, "obc": 100, "ews": 100, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Tier I (CBT) -> Tier II (CBT + Skill Test)", "pay": "Pay Level 2 to 4 (Rs 19,900 - 81,100)", "notif": -20, "applyStart": -18, "applyLast": 6, "exam": 70, "admit": 85, "pdf": null, "apply": "https://ssc.gov.in/notice/chsl-2026.pdf", "src": "https://ssc.gov.in/apply"},
  {"org": "UPSC", "title": "UPSC Civil Services Examination 2026", "titleHi": "यूपीएससी सिविल सेवा परीक्षा 2026", "summary": "Recruitment to IAS, IPS, IFS and other Group A and B central services.", "summaryHi": "आईएएस, आईपीएस, आईएफएस तथा अन्य केंद्रीय सेवाओं हेतु भर्ती।", "postNames": ["IAS", "IPS", "IFS", "IRS"], "adv": "UPSC/CSE/2026", "vacancies": 1129, "breakup": {"UR": 500, "OBC": 300, "SC": 170, "ST": 90, "EWS": 69}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Bachelor's degree in any discipline.", "streams": ["Any"], "minAge": 21, "maxAge": 32, "cutoff": 214, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 100, "obc": 100, "ews": 100, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Prelims -> Mains -> Interview", "pay": "Pay Level 10 (Rs 56,100 onwards)", "notif": -15, "applyStart": -14, "applyLast": 1, "exam": 80, "admit": 95, "pdf": null, "apply": "https://upsc.gov.in/notice/cse-2026.pdf", "src": "https://upsconline.nic.in"},
  {"org": "UPSC", "title": "UPSC Combined Defence Services Examination (II) 2026", "titleHi": "यूपीएससी संयुक्त रक्षा सेवा परीक्षा (II) 2026", "summary": "Officer entry into Indian Military Academy, Naval Academy, Air Force Academy and OTA.", "summaryHi": "आईएमए, नौसेना अकादमी, वायुसेना अकादमी और ओटीए में अधिकारी भर्ती।", "postNames": ["Officer Cadet"], "adv": "UPSC/CDS-II/2026", "vacancies": 459, "breakup": {"UR": 250, "OBC": 110, "SC": 60, "ST": 24, "EWS": 15}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduate; engineering degree for AFA and Naval Academy.", "streams": ["Any", "Engineering"], "minAge": 20, "maxAge": 25, "cutoff": 150, "relax": {"sc_st": 0, "obc": 0, "pwbd": 0, "esm": 0}, "exp": 0, "fees": {"general": 200, "obc": 200, "ews": 200, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Written Exam -> SSB Interview -> Medical", "pay": "Rs 56,100 during training", "notif": -9, "applyStart": -8, "applyLast": 12, "exam": 95, "admit": 110, "pdf": null, "apply": "https://upsc.gov.in/notice/cds2-2026.pdf", "src": "https://upsconline.nic.in"},
  {"org": "IBPS", "title": "IBPS Probationary Officer / Management Trainee CRP XVI", "titleHi": "आईबीपीएस प्रोबेशनरी ऑफिसर सीआरपी XVI", "summary": "Common recruitment for PO/MT posts in participating public sector banks.", "summaryHi": "सार्वजनिक क्षेत्र के बैंकों में पीओ/एमटी पदों हेतु सामान्य भर्ती।", "postNames": ["Probationary Officer", "Management Trainee"], "adv": "IBPS/CRP-PO/XVI", "vacancies": 5208, "breakup": {"UR": 2100, "OBC": 1400, "SC": 780, "ST": 400, "EWS": 528}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduation in any discipline with computer literacy.", "streams": ["Any"], "minAge": 20, "maxAge": 30, "cutoff": 60, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 850, "obc": 850, "ews": 850, "sc": 175, "st": 175, "female": 850, "pwbd": 175}, "selection": "Prelims -> Mains -> Interview", "pay": "JMGS-I, Rs 48,480 basic", "notif": -8, "applyStart": -7, "applyLast": 5, "exam": 40, "admit": 52, "pdf": null, "apply": "https://ibps.in/notice/po-xvi.pdf", "src": "https://ibps.in/apply"},
  {"org": "IBPS", "title": "IBPS Clerk (Customer Service Associate) CRP XVI", "titleHi": "आईबीपीएस क्लर्क सीआरपी XVI", "summary": "Clerical cadre recruitment across participating public sector banks.", "summaryHi": "सार्वजनिक बैंकों में लिपिक संवर्ग की भर्ती।", "postNames": ["Customer Service Associate"], "adv": "IBPS/CRP-CSA/XVI", "vacancies": 6128, "breakup": {"UR": 2500, "OBC": 1650, "SC": 920, "ST": 450, "EWS": 608}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduation in any discipline.", "streams": ["Any"], "minAge": 20, "maxAge": 28, "cutoff": 60, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 850, "obc": 850, "ews": 850, "sc": 175, "st": 175, "female": 850, "pwbd": 175}, "selection": "Prelims -> Mains", "pay": "Rs 24,050 - 64,480", "notif": -30, "applyStart": -28, "applyLast": -2, "exam": 50, "admit": 62, "pdf": null, "apply": "https://ibps.in/notice/clerk-xvi.pdf", "src": "https://ibps.in/apply"},
  {"org": "SBI", "title": "SBI Junior Associate (Clerk) Recruitment 2026", "titleHi": "एसबीआई जूनियर एसोसिएट (क्लर्क) भर्ती 2026", "summary": "Recruitment of Junior Associates in customer support and sales across SBI circles.", "summaryHi": "एसबीआई में जूनियर एसोसिएट पदों पर भर्ती।", "postNames": ["Junior Associate"], "adv": "CRPD/CR/2026-27/01", "vacancies": 13735, "breakup": {"UR": 5600, "OBC": 3600, "SC": 2050, "ST": 1100, "EWS": 1385}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduation in any discipline as on last date.", "streams": ["Any"], "minAge": 20, "maxAge": 28, "cutoff": 90, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 750, "obc": 750, "ews": 750, "sc": 0, "st": 0, "female": 750, "pwbd": 0}, "selection": "Prelims -> Mains -> Local language test", "pay": "Rs 26,730 - 64,480", "notif": -6, "applyStart": -5, "applyLast": 3, "exam": 42, "admit": 55, "pdf": null, "apply": "https://sbi.co.in/notice/clerk-2026.pdf", "src": "https://sbi.co.in/careers"},
  {"org": "SBI", "title": "SBI Probationary Officer Recruitment 2026", "titleHi": "एसबीआई प्रोबेशनरी ऑफिसर भर्ती 2026", "summary": "Recruitment of Probationary Officers in State Bank of India.", "summaryHi": "भारतीय स्टेट बैंक में प्रोबेशनरी ऑफिसर की भर्ती।", "postNames": ["Probationary Officer"], "adv": "CRPD/PO/2026-27/03", "vacancies": 600, "breakup": {"UR": 250, "OBC": 160, "SC": 90, "ST": 45, "EWS": 55}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduation in any discipline. Final year students may apply.", "streams": ["Any"], "minAge": 21, "maxAge": 30, "cutoff": 90, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 750, "obc": 750, "ews": 750, "sc": 0, "st": 0, "female": 750, "pwbd": 0}, "selection": "Prelims -> Mains -> Psychometric + Interview", "pay": "JMGS-I Rs 48,480 basic", "notif": -3, "applyStart": -1, "applyLast": 25, "exam": 65, "admit": 78, "pdf": null, "apply": "https://sbi.co.in/notice/po-2026.pdf", "src": "https://sbi.co.in/careers"},
  {"org": "LIC", "title": "LIC Assistant Administrative Officer (Generalist) 2026", "titleHi": "एलआईसी सहायक प्रशासनिक अधिकारी 2026", "summary": "Recruitment of AAO (Generalist, Chartered Accountant and Legal streams).", "summaryHi": "एएओ (सामान्य, सीए और विधि) पदों पर भर्ती।", "postNames": ["Assistant Administrative Officer"], "adv": "LIC/AAO/2026", "vacancies": 1200, "breakup": {"UR": 500, "OBC": 320, "SC": 180, "ST": 90, "EWS": 110}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Bachelor's degree in any discipline from a recognised university.", "streams": ["Any", "Commerce", "Law"], "minAge": 21, "maxAge": 30, "cutoff": 60, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 700, "obc": 700, "ews": 700, "sc": 85, "st": 85, "female": 700, "pwbd": 85}, "selection": "Prelims -> Mains -> Interview -> Pre-recruitment medical", "pay": "Rs 88,635 basic pay", "notif": -5, "applyStart": -4, "applyLast": 7, "exam": 38, "admit": 50, "pdf": null, "apply": "https://licindia.in/notice/aao-2026.pdf", "src": "https://licindia.in/careers"},
  {"org": "RBI", "title": "RBI Grade B Officer (DR - General) 2026", "titleHi": "आरबीआई ग्रेड बी अधिकारी 2026", "summary": "Direct recruitment of Grade B Officers in the Reserve Bank of India.", "summaryHi": "भारतीय रिज़र्व बैंक में ग्रेड बी अधिकारियों की सीधी भर्ती।", "postNames": ["Officer Grade B (DR)"], "adv": "RBI/GRB/2026", "vacancies": 94, "breakup": {"UR": 40, "OBC": 25, "SC": 14, "ST": 7, "EWS": 8}, "state": "All India", "location": "Mumbai", "qual": "graduate", "qualDetails": "Minimum 60% marks in graduation (50% for SC/ST/PwBD).", "streams": ["Any"], "minAge": 21, "maxAge": 30, "cutoff": 30, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 850, "obc": 850, "ews": 850, "sc": 100, "st": 100, "female": 850, "pwbd": 100}, "selection": "Phase I -> Phase II -> Interview", "pay": "Rs 55,200 basic pay", "notif": -4, "applyStart": -3, "applyLast": 10, "exam": 48, "admit": 60, "pdf": null, "apply": "https://rbi.org.in/notice/gradeb-2026.pdf", "src": "https://opportunities.rbi.org.in"},
  {"org": "RRB", "title": "RRB Non-Technical Popular Categories (NTPC) Graduate Level 2026", "titleHi": "आरआरबी एनटीपीसी स्नातक स्तर 2026", "summary": "Recruitment to Station Master, Goods Train Manager, Clerk cum Typist and other posts.", "summaryHi": "स्टेशन मास्टर, गुड्स ट्रेन मैनेजर तथा अन्य पदों पर भर्ती।", "postNames": ["Station Master", "Goods Train Manager", "Chief Commercial cum Ticket Supervisor"], "adv": "CEN 05/2026", "vacancies": 8113, "breakup": {"UR": 3300, "OBC": 2100, "SC": 1200, "ST": 600, "EWS": 913}, "state": "All India", "location": "All India", "qual": "graduate", "qualDetails": "Graduation in any discipline from a recognised university.", "streams": ["Any"], "minAge": 18, "maxAge": 33, "cutoff": 30, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 3}, "exp": 0, "fees": {"general": 500, "obc": 500, "ews": 500, "sc": 250, "st": 250, "female": 250, "pwbd": 250}, "selection": "CBT 1 -> CBT 2 -> Typing/Aptitude -> DV -> Medical", "pay": "Pay Level 2 to 6", "notif": -10, "applyStart": -9, "applyLast": 4, "exam": 55, "admit": 68, "pdf": null, "apply": "https://indianrailways.gov.in/notice/ntpc-2026.pdf", "src": "https://rrbapply.gov.in"},
  {"org": "RRB", "title": "RRB Level 1 (Group D) Recruitment 2026", "titleHi": "आरआरबी लेवल 1 (ग्रुप डी) भर्ती 2026", "summary": "Recruitment to Track Maintainer, Pointsman, Assistant and other Level 1 posts.", "summaryHi": "ट्रैक मेंटेनर, पॉइंट्समैन तथा अन्य लेवल 1 पदों पर भर्ती।", "postNames": ["Track Maintainer Grade IV", "Pointsman", "Assistant (Workshop)"], "adv": "CEN 08/2026", "vacancies": 32438, "breakup": {"UR": 13000, "OBC": 8700, "SC": 4900, "ST": 2400, "EWS": 3438}, "state": "All India", "location": "All India", "qual": "10th", "qualDetails": "10th pass or ITI or NAC granted by NCVT.", "streams": ["Any", "ITI"], "minAge": 18, "maxAge": 36, "cutoff": 30, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 3}, "exp": 0, "fees": {"general": 500, "obc": 500, "ews": 500, "sc": 250, "st": 250, "female": 250, "pwbd": 250}, "selection": "CBT -> Physical Efficiency Test -> DV -> Medical", "pay": "Pay Level 1 (Rs 18,000)", "notif": -25, "applyStart": -24, "applyLast": 20, "exam": 75, "admit": 88, "pdf": null, "apply": "https://indianrailways.gov.in/notice/groupd-2026.pdf", "src": "https://rrbapply.gov.in"},
  {"org": "ARMY", "title": "Indian Army Agniveer General Duty Rally 2026", "titleHi": "भारतीय सेना अग्निवीर जनरल ड्यूटी रैली 2026", "summary": "Agnipath scheme recruitment of Agniveer (General Duty) through online CEE and rally.", "summaryHi": "अग्निपथ योजना के अंतर्गत अग्निवीर (जीडी) की भर्ती।", "postNames": ["Agniveer (General Duty)"], "adv": "ARO/AGNIVEER/GD/2026", "vacancies": 25000, "breakup": {"UR": 10000, "OBC": 6800, "SC": 3800, "ST": 1900, "EWS": 2500}, "state": "All India", "location": "All India", "qual": "10th", "qualDetails": "10th pass with 45% aggregate and 33% in each subject.", "streams": ["Any"], "minAge": 17, "maxAge": 21, "cutoff": 30, "relax": {"sc_st": 0, "obc": 0, "pwbd": 0, "esm": 0}, "exp": 0, "fees": {"general": 250, "obc": 250, "ews": 250, "sc": 250, "st": 250, "female": 250, "pwbd": 250}, "selection": "Online CEE -> Physical Fitness Test -> Medical -> Merit List", "pay": "Rs 30,000 per month in year 1", "notif": -7, "applyStart": -6, "applyLast": 9, "exam": 44, "admit": 56, "pdf": null, "apply": "https://joinindianarmy.nic.in/notice/agniveer-gd.pdf", "src": "https://joinindianarmy.nic.in"},
  {"org": "NAVY", "title": "Indian Navy Agniveer SSR 02/2026 Batch", "titleHi": "भारतीय नौसेना अग्निवीर एसएसआर 02/2026", "summary": "Recruitment of Agniveer (Senior Secondary Recruit) in the Indian Navy.", "summaryHi": "भारतीय नौसेना में अग्निवीर (एसएसआर) की भर्ती।", "postNames": ["Agniveer SSR"], "adv": "NAVY/SSR/02/2026", "vacancies": 2800, "breakup": {"UR": 1150, "OBC": 760, "SC": 420, "ST": 210, "EWS": 260}, "state": "All India", "location": "All India", "qual": "12th", "qualDetails": "12th pass with Maths and Physics, plus one of Chemistry/Biology/Computer Science.", "streams": ["Science"], "minAge": 17, "maxAge": 21, "cutoff": 45, "relax": {"sc_st": 0, "obc": 0, "pwbd": 0, "esm": 0}, "exp": 0, "fees": {"general": 550, "obc": 550, "ews": 550, "sc": 550, "st": 550, "female": 550, "pwbd": 550}, "selection": "INET (CBT) -> PFT -> Medical", "pay": "Rs 30,000 per month in year 1", "notif": -2, "applyStart": 0, "applyLast": 30, "exam": 72, "admit": 84, "pdf": null, "apply": "https://joinindiannavy.gov.in/notice/ssr-2026.pdf", "src": "https://joinindiannavy.gov.in"},
  {"org": "NTPC", "title": "NTPC Executive Trainee (Engineering) 2026 through GATE", "titleHi": "एनटीपीसी कार्यकारी प्रशिक्षु (अभियांत्रिकी) 2026", "summary": "Executive Trainee recruitment in Mechanical, Electrical, Civil, C and I and Electronics through GATE.", "summaryHi": "गेट के माध्यम से कार्यकारी प्रशिक्षु की भर्ती।", "postNames": ["Executive Trainee"], "adv": "NTPC/ET/2026/01", "vacancies": 400, "breakup": {"UR": 165, "OBC": 108, "SC": 60, "ST": 30, "EWS": 37}, "state": "All India", "location": "All India", "qual": "engineering", "qualDetails": "Full-time BE/BTech with 65% marks and a valid GATE 2026 score.", "streams": ["Mechanical", "Electrical", "Civil", "Electronics", "Instrumentation"], "minAge": 18, "maxAge": 27, "cutoff": 60, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 0, "fees": {"general": 300, "obc": 300, "ews": 300, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "GATE 2026 score -> Group Discussion -> Personal Interview", "pay": "E2 grade, Rs 60,000 - 1,80,000", "notif": -6, "applyStart": -5, "applyLast": 14, "exam": null, "admit": null, "pdf": null, "apply": "https://ntpc.co.in/notice/et-2026.pdf", "src": "https://careers.ntpc.co.in"},
  {"org": "ONGC", "title": "ONGC Graduate Trainee (Non-Executive) Recruitment 2026", "titleHi": "ओएनजीसी ग्रेजुएट ट्रेनी भर्ती 2026", "summary": "Recruitment of graduate and diploma trainees at ONGC work centres across India.", "summaryHi": "ओएनजीसी कार्य केंद्रों पर ग्रेजुएट एवं डिप्लोमा ट्रेनी की भर्ती।", "postNames": ["Graduate Trainee", "Junior Assistant Technician"], "adv": "ONGC/GT/2026", "vacancies": 2200, "breakup": {"UR": 900, "OBC": 600, "SC": 330, "ST": 165, "EWS": 205}, "state": "All India", "location": "All India", "qual": "diploma", "qualDetails": "Diploma in Engineering or graduation as per post-wise requirement.", "streams": ["Mechanical", "Electrical", "Chemical", "Petroleum"], "minAge": 18, "maxAge": 30, "cutoff": 60, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5}, "exp": 1, "fees": {"general": 300, "obc": 300, "ews": 300, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "CBT -> Document Verification -> Medical", "pay": "Rs 25,000 - 1,05,000", "notif": -11, "applyStart": -10, "applyLast": 18, "exam": 66, "admit": 79, "pdf": null, "apply": "https://ongcindia.com/notice/gt-2026.pdf", "src": "https://ongcindia.com/careers"},
  {"org": "BPSC", "title": "BPSC 71st Combined Competitive Examination", "titleHi": "बीपीएससी 71वीं संयुक्त प्रतियोगी परीक्षा", "summary": "Bihar state civil services recruitment including SDM, DSP and other posts.", "summaryHi": "बिहार राज्य सिविल सेवा में एसडीएम, डीएसपी आदि पदों पर भर्ती।", "postNames": ["Sub Divisional Magistrate", "Deputy Superintendent of Police", "Revenue Officer"], "adv": "BPSC/71/2026", "vacancies": 1250, "breakup": {"UR": 500, "OBC": 340, "SC": 190, "ST": 20, "EWS": 200}, "state": "Bihar", "location": "Bihar", "qual": "graduate", "qualDetails": "Graduation in any discipline from a recognised university.", "streams": ["Any"], "minAge": 20, "maxAge": 37, "cutoff": 1, "relax": {"sc_st": 5, "obc": 3, "pwbd": 10, "esm": 5, "female": 3}, "exp": 0, "fees": {"general": 600, "obc": 600, "ews": 600, "sc": 150, "st": 150, "female": 150, "pwbd": 150}, "selection": "Prelims -> Mains -> Interview", "pay": "Pay Level 9 (Rs 53,100 onwards)", "notif": -14, "applyStart": -12, "applyLast": 8, "exam": 58, "admit": 70, "pdf": null, "apply": "https://bpsc.bih.nic.in/notice/71cce.pdf", "src": "https://onlinebpsc.bihar.gov.in"},
  {"org": "UPPSC", "title": "UPPSC Provincial Civil Services (PCS) Examination 2026", "titleHi": "यूपीपीएससी प्रांतीय सिविल सेवा परीक्षा 2026", "summary": "Uttar Pradesh state civil services recruitment for administrative and police posts.", "summaryHi": "उत्तर प्रदेश राज्य सिविल सेवा भर्ती।", "postNames": ["Deputy Collector", "Deputy SP", "Block Development Officer"], "adv": "UPPSC/PCS/2026", "vacancies": 930, "breakup": {"UR": 380, "OBC": 250, "SC": 190, "ST": 18, "EWS": 92}, "state": "Uttar Pradesh", "location": "Uttar Pradesh", "qual": "graduate", "qualDetails": "Bachelor's degree in any discipline.", "streams": ["Any"], "minAge": 21, "maxAge": 40, "cutoff": 1, "relax": {"sc_st": 5, "obc": 3, "pwbd": 15, "esm": 5, "female": 5}, "exp": 0, "fees": {"general": 125, "obc": 125, "ews": 125, "sc": 65, "st": 65, "female": 125, "pwbd": 25}, "selection": "Prelims -> Mains -> Interview", "pay": "Pay Level 9 to 11", "notif": -13, "applyStart": -11, "applyLast": 11, "exam": 62, "admit": 74, "pdf": null, "apply": "https://uppsc.up.nic.in/notice/pcs-2026.pdf", "src": "https://uppsc.up.nic.in/apply"},
  {"org": "MPPSC", "title": "MPPSC State Engineering Service Examination 2026", "titleHi": "एमपीपीएससी राज्य अभियांत्रिकी सेवा परीक्षा 2026", "summary": "Recruitment of Assistant Engineers in Madhya Pradesh government departments.", "summaryHi": "मध्य प्रदेश शासन विभागों में सहायक यंत्री की भर्ती।", "postNames": ["Assistant Engineer (Civil)", "Assistant Engineer (Electrical)"], "adv": "MPPSC/SES/2026", "vacancies": 312, "breakup": {"UR": 120, "OBC": 85, "SC": 50, "ST": 40, "EWS": 17}, "state": "Madhya Pradesh", "location": "Madhya Pradesh", "qual": "engineering", "qualDetails": "BE/BTech in the relevant engineering branch.", "streams": ["Civil", "Electrical", "Mechanical"], "minAge": 21, "maxAge": 40, "cutoff": 1, "relax": {"sc_st": 5, "obc": 5, "pwbd": 10, "esm": 5, "female": 5}, "exp": 0, "fees": {"general": 500, "obc": 250, "ews": 500, "sc": 250, "st": 250, "female": 250, "pwbd": 250}, "selection": "Written Examination -> Interview", "pay": "Pay Level 12 (Rs 56,100)", "notif": -5, "applyStart": 15, "applyLast": 40, "exam": 90, "admit": 105, "pdf": null, "apply": "https://mppsc.mp.gov.in/notice/ses-2026.pdf", "src": "https://mppsc.mp.gov.in/apply"},
  {"org": "INFOSYS", "title": "Infosys Systems Engineer Off-Campus Drive 2026", "titleHi": "इन्फोसिस सिस्टम्स इंजीनियर ऑफ-कैंपस ड्राइव 2026", "summary": "Verified private sector hiring for Systems Engineer roles for 2026 graduates.", "summaryHi": "2026 बैच के स्नातकों के लिए सत्यापित निजी क्षेत्र भर्ती।", "postNames": ["Systems Engineer", "Digital Specialist Engineer"], "adv": "INFY/SE/2026", "vacancies": 1500, "breakup": {"General": 1500}, "state": "Karnataka", "location": "Bengaluru, Pune, Hyderabad, Mysuru", "qual": "engineering", "qualDetails": "BE/BTech/MCA with 60% throughout academics, 2026 batch.", "streams": ["Computer Science", "Information Technology", "Electronics"], "minAge": 20, "maxAge": 26, "cutoff": null, "relax": {}, "exp": 0, "fees": {"general": 0, "obc": 0, "ews": 0, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Online Assessment -> Technical Interview -> HR Interview", "pay": "Rs 3.6 - 6.5 LPA", "notif": -4, "applyStart": -3, "applyLast": 13, "exam": 35, "admit": null, "pdf": null, "apply": "https://infosys.com/careers/se-2026.pdf", "src": "https://career.infosys.com"},
  {"org": "TATAMOTORS", "title": "Tata Motors Diploma Trainee Engineer Recruitment 2026", "titleHi": "टाटा मोटर्स डिप्लोमा ट्रेनी इंजीनियर भर्ती 2026", "summary": "Verified private sector hiring of diploma trainees for manufacturing plants.", "summaryHi": "विनिर्माण संयंत्रों हेतु डिप्लोमा ट्रेनी की सत्यापित भर्ती।", "postNames": ["Diploma Trainee Engineer"], "adv": "TML/DTE/2026", "vacancies": 450, "breakup": {"General": 450}, "state": "Maharashtra", "location": "Pune, Jamshedpur, Lucknow", "qual": "diploma", "qualDetails": "3-year Diploma in Mechanical, Electrical, Production or Automobile with 60%.", "streams": ["Mechanical", "Electrical", "Production", "Automobile"], "minAge": 18, "maxAge": 25, "cutoff": null, "relax": {}, "exp": 0, "fees": {"general": 0, "obc": 0, "ews": 0, "sc": 0, "st": 0, "female": 0, "pwbd": 0}, "selection": "Online Test -> Technical Interview -> Medical", "pay": "Rs 2.4 - 3.2 LPA stipend", "notif": -8, "applyStart": -7, "applyLast": 2, "exam": 30, "admit": null, "pdf": null, "apply": "https://tatamotors.com/careers/dte-2026.pdf", "src": "https://tatamotors.com/careers"},
];

export const SEED_ORGS = [
  { name: "Staff Selection Commission", shortName: "SSC", sector: "central_govt", state: null, officialWebsite: "https://ssc.gov.in" },
  { name: "Union Public Service Commission", shortName: "UPSC", sector: "central_govt", state: null, officialWebsite: "https://upsc.gov.in" },
  { name: "Institute of Banking Personnel Selection", shortName: "IBPS", sector: "banking_insurance", state: null, officialWebsite: "https://ibps.in" },
  { name: "State Bank of India", shortName: "SBI", sector: "banking_insurance", state: null, officialWebsite: "https://sbi.co.in" },
  { name: "Life Insurance Corporation of India", shortName: "LIC", sector: "banking_insurance", state: null, officialWebsite: "https://licindia.in" },
  { name: "Reserve Bank of India", shortName: "RBI", sector: "banking_insurance", state: null, officialWebsite: "https://rbi.org.in" },
  { name: "Railway Recruitment Board", shortName: "RRB", sector: "railways", state: null, officialWebsite: "https://indianrailways.gov.in" },
  { name: "Indian Army", shortName: "ARMY", sector: "defence", state: null, officialWebsite: "https://joinindianarmy.nic.in" },
  { name: "Indian Navy", shortName: "NAVY", sector: "defence", state: null, officialWebsite: "https://joinindiannavy.gov.in" },
  { name: "NTPC Limited", shortName: "NTPC", sector: "psu", state: null, officialWebsite: "https://ntpc.co.in" },
  { name: "Oil and Natural Gas Corporation", shortName: "ONGC", sector: "psu", state: null, officialWebsite: "https://ongcindia.com" },
  { name: "Bihar Public Service Commission", shortName: "BPSC", sector: "state_psc", state: "Bihar", officialWebsite: "https://bpsc.bihar.gov.in" },
  { name: "Uttar Pradesh Public Service Commission", shortName: "UPPSC", sector: "state_psc", state: "Uttar Pradesh", officialWebsite: "https://uppsc.up.nic.in" },
  { name: "Madhya Pradesh Public Service Commission", shortName: "MPPSC", sector: "state_psc", state: "Madhya Pradesh", officialWebsite: "https://mppsc.mp.gov.in" },
  { name: "Infosys Limited", shortName: "INFOSYS", sector: "private", state: "Karnataka", officialWebsite: "https://infosys.com" },
  { name: "Tata Motors Limited", shortName: "TATAMOTORS", sector: "private", state: "Maharashtra", officialWebsite: "https://tatamotors.com" },
];

// Starter list of official pages the scraper watches. These are real official domains, but
// page layouts change often: check each in Admin -> Sources, run it once, and adjust the
// URL / link selector / include pattern if it finds nothing. Add more from the admin panel.
export const SEED_SOURCES = [
  { org: "SSC", name: "SSC - Notice board", url: "https://ssc.gov.in/", sector: "central_govt" },
  { org: "UPSC", name: "UPSC - Recruitment advertisements", url: "https://upsc.gov.in/recruitment/recruitment-advertisement", sector: "central_govt" },
  { org: "UPSC", name: "UPSC - Examination notifications", url: "https://upsc.gov.in/examinations/active-exams", sector: "central_govt" },
  { org: "IBPS", name: "IBPS - Home announcements", url: "https://www.ibps.in/", sector: "banking_insurance" },
  { org: "SBI", name: "SBI - Current openings", url: "https://sbi.co.in/web/careers/current-openings", sector: "banking_insurance" },
  { org: "RBI", name: "RBI - Current vacancies", url: "https://opportunities.rbi.org.in/Scripts/Vacancies.aspx", sector: "banking_insurance" },
  { org: "LIC", name: "LIC - Careers", url: "https://licindia.in/careers", sector: "banking_insurance" },
  { org: "RRB", name: "RRB Chandigarh - Notices (mirrors all RRB CENs)", url: "https://www.rrbcdg.gov.in/", sector: "railways" },
  { org: "ARMY", name: "Join Indian Army - Notifications", url: "https://joinindianarmy.nic.in/", sector: "defence" },
  { org: "NAVY", name: "Join Indian Navy - Current opportunities", url: "https://www.joinindiannavy.gov.in/", sector: "defence" },
  { org: "NTPC", name: "NTPC - Careers", url: "https://careers.ntpc.co.in/recruitment/", sector: "psu" },
  { org: "ONGC", name: "ONGC - Careers", url: "https://ongcindia.com/web/eng/careers", sector: "psu" },
  { org: "BPSC", name: "BPSC - Advertisements", url: "https://bpsc.bihar.gov.in/", sector: "state_psc" },
  { org: "UPPSC", name: "UPPSC - Advertisements", url: "https://uppsc.up.nic.in/", sector: "state_psc" },
  { org: "MPPSC", name: "MPPSC - Advertisements", url: "https://mppsc.mp.gov.in/", sector: "state_psc" },
  { org: "INFOSYS", name: "Infosys - Careers (official)", url: "https://www.infosys.com/careers/", sector: "private" },
];

export const SEED_UPDATES = [
  { adv: "SSC/CGL/01/2026", type: "date_extension", title: "Last date extended by 7 days vide corrigendum", daysAgo: 2 },
  { adv: "CEN 05/2026", type: "corrigendum", title: "Corrigendum: revised vacancy breakup for OBC category", daysAgo: 4 },
  { adv: "IBPS/CRP-PO/XVI", type: "admit_card", title: "Admit card release date announced", daysAgo: 1 },
];
